### ISSUE TITLE
Not able to run spark 

### ISSUE THREAD

**Issue by skoushik13** [mapr/mapr-demos#2]
Hi,

I am getting below error when I am trying to run the rt_profile_dash.py, Please can you let me know what I am doing wrong here.

[user01@maprdemo spark_music_demo]$ /opt/mapr/spark/spark-1.3.1/bin/spark-submit ./rt_profile_dash.py
Traceback (most recent call last):  
  File "/user/user01/mapr/spark_music_demo/./rt_profile_dash.py", line 125, in <module>
    'adata:mobile_tracks': str(aggdata.mean()[5]) })
  File "/usr/lib/python2.6/site-packages/happybase/table.py", line 439, in put
    batch.put(row, data)
  File "/usr/lib/python2.6/site-packages/happybase/batch.py", line 132, in **exit**
    self.send()
  File "/usr/lib/python2.6/site-packages/happybase/batch.py", line 55, in send
    self._table.connection.client.mutateRows(self._table.name, bms, {})
  File "/usr/lib/python2.6/site-packages/happybase/hbase/Hbase.py", line 1576, in mutateRows
    self.recv_mutateRows()
  File "/usr/lib/python2.6/site-packages/happybase/hbase/Hbase.py", line 1599, in recv_mutateRows
    raise result.io
happybase.hbase.ttypes.IOError: IOError(_message=None)

**Comment by namato** [comment]
Hi there, it looks like this is a problem with happybase connecting to HBase.  It is not clear what is happening from the error message.  Check that the hbase-thriftserver package is installed and running on the node where you are connecting, and that you can connect to port 9090 from the machine(s) running Spark.
